name: Scrape Loko Fixtures

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 6 * * 5"  # каждую пятницу 06:00 UTC (~ 09:00 по Хельсинки)

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install chromium --with-deps

      - name: Run scraper
        run: npm start

      - name: Commit fixtures.json and diagnostics
        run: |
          git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add fixtures.json debug-schedule.txt debug-tickets.txt || true
    git commit -m "Update fixtures + debug [skip ci]" || echo "No changes"
    git push
